### ISSUE TITLE
HFWS # 1007 Download Fails

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#112]
HFWS # 1007 download fails when attempting to download the hymn sheet and PowerPoint slides.

**Comment by rodydavis** [comment]
Can you test with https://hymnsforworship.app?

Version 4 is live and should fix this

**Comment by alanmsings** [comment]
I was able to view the hymn in hymnal form and PowerPoint slides via the
link.

However, I am still unable to view The Hymns sheet or PowerPoint slides in
the app. I have the following version of the iOS app.


When will Version 4 for iOS go live?

I’ve also noted an additional issue. Please see the screenshot below.


This occurs via the web link and in the app. I am a Pro Subscriber

**Comment by rodydavis** [comment]
I do not see any screenshots on the GitHub issue. You will have to drag them onto the input text box.

Version 4 is in beta and should be live after I test it more when I get back from India in a week or two

**Comment by alanmsings** [comment]
![image](https://github.com/user-attachments/assets/d032b905-2d7c-4062-8e85-8b072a645874)![image](https://github.com/user-attachments/assets/4a29a1fc-1bb1-4de3-b868-c7b4a48a6767)

**Comment by rodydavis** [comment]
Version 4 is rolling out for Android and iOS this week!

**Comment by alanmsings** [comment]
Will the app have an option to purchase .pdfs for printing? I would be willing to pay more as part of a subscription to have access for printing .pdfs as needed. Would you be willing to consider on demand .pdf printing as a subscription option?

**Comment by alanmsings** [comment]
In Version 3.2, hymns were separated according to hymnal and accessed by clicking the hymnal icon. I found this functionality helpful in preparing my song service because it allows easy access to each hymnal and made planning song services from one hymnal quicker. Would you consider adding this functionality back to future versions?

The filter option is not working or I am entering the required filter incorrectly.

**Comment by rodydavis** [comment]
You can search a song, and then go to the bottom of the details and tap on the hymnal, then it will go back to the list and search all songs by the hymnal.

I want to make that easier to do in filters but is totally possible now.

For PDF it will be coming soon but require individual hymn purchases on the website from rjstevensmusic. If you long with the same email as the account on the website it will transfer over.

**Comment by rodydavis** [comment]
On demand PDF printing is being discussed
