### ISSUE TITLE
Login/account help

### ISSUE THREAD

**Issue by meadows8654** [hymns-for-worship/issues#162]
Good afternoon,
It is not letting me log into the app. Keeps saying no account found. I am a yearly subscriber, have tried deleting then reinstalling, have updated to change log 4.8.0+873, and tried recovering account, all with no luck.
Thank you, 
Mark Meadows 
meadows8654@gmail.com

![Image](https://github.com/user-attachments/assets/fe646631-8f24-4bba-9f94-0c6e621b3ef8)

**Comment by rodydavis** [comment]
<img width="552" alt="Image" src="https://github.com/user-attachments/assets/a1af869f-2ee6-438a-8d65-3d756c167a4c" />

Looks like there where multiple emails sent. Did the reset not work?

**Comment by rodydavis** [comment]
Please test again, the database was full and needed to resize the server

**Comment by meadows8654** [comment]
I tried again just now, no luck. Also tired to reset password and it says “email sent” but I haven’t received a password reset email any of the times I’ve requested it, also not in my spam or junk box.

**Comment by rodydavis** [comment]
Try tomorrow morning if possible. I switched the server to a way bigger instance and need the DNS to propagate.

It should work now though!

**Comment by rodydavis** [comment]
If it is still broken tomorrow I can manually reset

**Comment by meadows8654** [comment]
Good morning. 
Sorry, still no luck. 

![Image](https://github.com/user-attachments/assets/316510d1-be05-4532-acc4-95d7c5c4228b)

**Comment by rodydavis** [comment]
Please restart the app and try again!

**Comment by rodydavis** [comment]
I am also rolling out an update to fix it!

**Comment by rodydavis** [comment]
If you were having issues trying to send the verify email and did not get it, please try it again! We changed email providers and should be working now

**Comment by meadows8654** [comment]
That worked! Thank you so much!

**Comment by rodydavis** [comment]
You are welcome!
